# Generated by Django 3.1.1 on 2020-10-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleForecastHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(auto_now_add=True)),
                ('max_temperature', models.FloatField(verbose_name='최고기온')),
                ('min_temperature', models.FloatField(verbose_name='최저기온')),
                ('x', models.IntegerField(verbose_name='예보지점 X좌표')),
                ('y', models.IntegerField(verbose_name='예보지점 Y좌표')),
            ],
            options={
                'unique_together': {('forecast_date', 'x', 'y')},
            },
        ),
    ]
